enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan Villela"

disableKinds = ["taxonomyTerm"]
FootnoteReturnLinkContents = "↩"
metaDataFormat = "yaml"
summarylength = 40

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsOptions = "lineseparator=<br>"
pygmentsStyle = "dracula"
pygmentsUseClasses = true
pygmentsUseClassic = false

[author]
  name = "Juan Villela"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true
  OpenLinksInNewWindow = true

[params]
  description = "Front-End Developer, automation nerd, and astronomy enthusiast."
  social = "fourjuaneight"

[taxonomies]
  tags = "tags"

[permalinks]
  section = "/:filename/"
  blog = "/blog/:filename/"
  tags = "/tags/:slug/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputFormats.jsonfeed]
  MediaType = "application/json"
  BaseName = "feed"
  suffix = "json"
  IsHTML = false
  IsPlainText = true

[outputs]
  home = ["html"]
  section = ["html", "jsonfeed", "rss"]