language: node_js

os:
  - linux

dist: xenial

node_js:
  - 12.16.0

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_script:
  - npm ci

script:
  - npm run ci "cypress run --record --key $CYPRESS_KEY"
  - npm run test:unit

notifications:
  webhooks:
    urls:
      - $PUSHCUT_ENDPOINT
    on_success: never
    on_failure: always
