baseURL = "/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan C Villela"

FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"
disableKinds = ["taxonomyTerm"]
summarylength = 40

[taxonomies]
  tags = "tags"

[permalinks]
  section = "/:filename/"
  writing = "/writing/:filename/"
  tags = "/writing/tags/:slug/"

[author]
  name = "Juan C Villela"
  email = "info@juanvillela.dev"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  description = "I'm Juan Villela. I'm a web developer, automation and astronomy nerd currently working independently. I help businesses build accessible and performant static sites."
  social = "fourjuaneight"
  OpenLinksInNewWindow = true

[outputFormats.jsonfeed]
  MediaType = "application/json"
  BaseName = "feed"
  suffix = "json"
  IsHTML = false
  IsPlainText = true

[outputs]
  home = ["html"]
  section = ["html", "jsonfeed", "rss"]