baseURL = "/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan C Villela"

FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"
disableKinds = ["taxonomy", "taxonomyTerm"]
summarylength = 40

[permalinks]
  section = "/:filename/"
  writing = "/writing/:filename/"
  tags = "/writing/:slug/"

[taxonomies]
  tags = "tags"

[author]
  name = "Juan C Villela"
  email = "info@juanvillela.dev"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  description = "I'm Juan Villela. A Front-End developer with a focus on static sites based in Washington, DC."
  social = "fourjuaneight"
  OpenLinksInNewWindow = true

[outputFormats.jsonfeed]
  MediaType = "application/json"
  BaseName = "feed"
  suffix = "json"
  IsHTML = false
  IsPlainText = true

[outputs]
  home = ["html"]
  section = ["html", "jsonfeed", "rss"]