baseURL = "https://www.juanvillela.dev/"
enableEmoji = "true"
enableRobotsTXT = "true"
languageCode = "en-us"
title = "Juan C Villela"

FootnoteReturnLinkContents = "↩"
SectionPagesMenu = "main"
disableKinds = ["taxonomy", "taxonomyTerm"]
disableFastRender = true

[permalinks]
  section = "/:filename/"
  writing = "/writing/:filename/"
  tags = "/writing/:slug/"

[taxonomies]
  tags = "tags"

[author]
  name = "Juan C Villela"
  email = "info@juanvillela.dev"

[blackfriday]
  hrefTargetBlank = true
  plainIDAnchors = true

[params]
  description = "I'm Juan Villela. A Front-End developer with a focus on static sites based in Washington, DC."
  social = "fourjuaneight"
  OpenLinksInNewWindow = true

[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true

[outputs]
  home = ["html"]
  section = ["html"]
  writing = ["html", "jsonfeed"]