[build]
  publish = "public"
  command = "yarn build"

# Config for Github pull requests.
[context.deploy-preview]
  command = "yarn build"

# Default config for branch deploys.
[context.branch-deploy]
  # Build without minification & optimization.
  command = "yarn build"

# Custom config for the staging branch.
[context.staging]
  # We want a production-like build.
  command = "yarn build"

# Production config.
[context.production]
  command = "yarn build"
