[build]
  publish = "public"
  command = "npm run build"

# Config for Github pull requests.
[context.deploy-preview]
  command = "npm run development"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "development"

# Default config for branch deploys.
[context.development]
  command = "npm run development"

[context.staging]
  command = "npm run staging"

[context.development.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "development"

[context.staging.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "staging"

# Production config.
[context.production]
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"