name: Optimize Images
on: pull_request
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: calibreapp/image-actions
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    jpeg:
      quality: 90
    png:
      quality: 90
    webp:
      quality: 90
    ignorePaths:
      - "node_modules/**"
