name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.8.0

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Cypress
        uses: cypress-io/github-action@v1
        with:
          config-file: cypress.json
