name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: E2E Tests
        run: |
          npm ci
          npm run build:production
          npm run cy:headless
